- id: '1535912802202'
  alias: WakeUp
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state }}'

  condition: []
  action:
    service: light.turn_on
    entity_id: light.livingroom
    data:
      transition: 60
      brightness: 255
