- id: 'wake_up'
  alias: wake_up
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state }}'
  condition:
    condition: state
    entity_id: input_boolean.wake_up_switch
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.bedroom
    data:
      transition: 900
      brightness: 255

- id: 'wake_up_kids'
  alias: wake_up_kids
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time_2.state }}'
  condition:
    condition: state
    entity_id: input_boolean.wake_up_switch
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.kids
    data:
      transition: 900
      brightness: 255

- id: 'bed_time'
  alias: bed_time
  trigger:
  - at: '19:30'
    platform: time
  condition: []
  action:
    service: light.turn_on
    entity_id: light.kids
    data:
      brightness: 1

- id: 'night_light'
  alias: night_light
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
    service: light.turn_on
    entity_id: light.livingroom
    data:
      brightness: 1

- id: 'lights_off'
  alias: lights_off
  trigger:
  - at: '8:30'
    platform: time
  condition: []
  action:
    service: light.turn_off
    entity_id: group.all_lights

- id: 'lights_on_flower'
  alias: lights_on_flower
  trigger:
  - at: '10:00'
    platform: time
  condition: []
  action:
    service: switch.turn_on
    entity_id: switch.plug_flower

- id: 'lights_off_flower'
  alias: lights_off_flower
  trigger:
  - at: '16:00'
    platform: time
  condition: []
  action:
    service: switch.turn_off
    entity_id: switch.plug_flower  
