homeassistant:
# Name and basic info
  name: Home
  latitude: 64.9388024
  longitude: 25.4303833
  elevation: 10
  unit_system: metric
  time_zone: Europe/Helsinki
  customize: !include customize.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret api_key

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# config files
input_number: !include inputs_number.yaml 
input_boolean: !include inputs_boolean.yaml
sensor: !include sensors.yaml 
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
